# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
sudo add-apt-repository ppa:
   - ubuntu-toolchain-r/test -y;
   - sudo apt-get update -qq
   - sudo apt-get install g++-4.9
# Build steps
script:
  - make test
